script:
- npm install
- grunt build
deploy:
  provider: heroku
  api_key:
    secure: ij1vtQN4vCqMiX2l3wzustnSIC//BErYPea/ojp63LTCiJWFvYg9j+otfAxVvtJgdgXfrFQbBMKY3SJjzoAsjhHBxn2/Bek3SU1ciSuvj9MaC/egvtBzyDhrMxbUwClsoYOgp8rj2YG3Tg3eGReCfi0nW3qpvsGVEigLc34ioMc=
  app: sphero-docs
  on:
    repo: orbotix/DeveloperDocumentation
    branch: master
