script: grunt build
deploy:
  provider: divshot
  environment:
    master: development
    staging: staging
    production: production
  skip_cleanup: true
  api_key:
    secure: ZuSTe6BxH1jTviyQ7+xvskV21OgjS9vMbVHpE8b5epSlaCQv521qIlC52zz22SapTPRAz8gX7l0LEcZ5p8e3izLWNWnTXo9co89YVvlqexWb8bZEtpACXHX9GVuzp/8KDBNOJybGmV9ZUQ2J9AKU8mE31f9elZEcnrGrapIqet0=
